import React from "react";
import Head from "next/head";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import InputButton from "../../components/Buttons/InputButton";
import Link from "next/link";

const index = () => {
  return (
    <>
      <Header />
      <div className="sign-in">
        <Head>
          <title>Sign In</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="sign-in-content">
          <div className="sign-in-content-form">
            <h2>Login</h2>
            <form>
              <div className="sign-in-content-form-input-section">
                <label htmlFor="">Username and E-mail <span className="required">*</span> </label>
                <input type="text" name="" id="" />
              </div>
              <div className="sign-in-content-form-input-section">
                <label htmlFor="">Password <span className="required">*</span></label>
                <input type="password" name="" id="" />
              </div>
              <div className="sign-in-content-form-input-section-buttons">
                <InputButton message="Login"/>
                <input type="checkbox" name="Remember Me" />
                <label htmlFor="">Remember Me</label>
                </div>
            </form>
            <Link href={'/'}><a>Forgot your password?</a></Link>
          </div>
        </div>
        <Footer />
      </div>
    </>
  );
};

export default index;
