import React from 'react'
import Head from 'next/head'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import InputButton from '@/buttons/InputButton'
import Link from 'next/link'

const index = () => {
  return (
    <>
      <Header />
      <div className="forgot-password">
        <Head>
          <title>Forgot Password</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="forgot-password-content">
          <div className="forgot-password-content-form">
            <form>
              <p>Lost your password? Please enter your username or email adress. You will receive a link to create a new password via email.</p>
              <div className="forgot-password-content-form-input-section">
                <label htmlFor="">
                  Username and E-mail
                </label>
                <input type="text" name="" id="" />
              </div>
              <div className="forgot-password-content-form-input-section-buttons">
                <InputButton message="Reset Password" />
              </div>
            </form>
          </div>
        </div>
        <Footer />
      </div>
    </>
  )
}

export default index
