import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import AddProperty from '../components/Buttons/AddProperty'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Anasayfa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='background'></div>
      <header>
        <div className='logo'>
          <Image src='/talebevi.svg' width={157} height={40} />
        </div>
        <nav>
          <ul>
            <li>Home</li>
            <li>About</li>
            <li>Property</li>
            <li>Pages</li>
            <li>Blog</li>
            <li>Contact</li>
          </ul>
        </nav>
        <div>
          <div>
            icon
          </div>
          <div>
            icon
          </div>
          <div>
            icon
          </div>
          <div>
            icon
          </div>
          <div>
            <AddProperty message={'Add Property'} />
          </div>
        </div>
      </header>
    </div>
  )
}

export default Home
