import React, { Fragment } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import Layout from '@/layout/Layout'

const Home: NextPage = () => {
  return (
    <Fragment>
      <Header />
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className="landing-page">
          <div className="landing-page-background"></div>
        </div>
      </Layout>
      <Footer />
    </Fragment>
  )
}

export default Home
