import React, { Fragment } from 'react'
import Head from 'next/head'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import { LayoutProps } from '../../interfaces/GlobalInterface'

function Layout({ children, title }: LayoutProps) {
  return (
    <Fragment>
      <div className="wrapper">
        <Header />
        <Head>
          <title>{title} | Majengoo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {children}
        <Footer />
      </div>
    </Fragment>
  )
}

export default Layout
